%MATLAB Code from Sensor Array Analyzer App

%Generated by MATLAB 9.3 and Phased Array System Toolbox 3.5

%Generated on 21-Jun-2020 00:21:34

% Create a uniform rectangular array
h = phased.URA;
h.Size = [16 16];
h.ElementSpacing = [0.0025 0.0025];
h.Lattice = 'Rectangular';
h.ArrayNormal = 'x';
%Calculate Row Taper
sll = 30;
rwind = chebwin(16, sll)';
rwind = repmat(rwind,16,1);
%Calculate Column Taper
sll = 30;
cwind = chebwin(16, sll)';
cwind = repmat(cwind.',1,16);
%Calculate taper
wind = rwind.*cwind;
h.Taper = wind;
%Create Cosine Antenna Element
el = phased.CosineAntennaElement;
el.CosinePower = [1 1];
h.Element = el;
%Assign steering angles, frequencies and propagation speed
SA = [30;30];
%Assign number of phase shift quantization bits
PSB = 0;
F = 66000000000;
PS = 300000000;
%Create figure, panel, and axes
fig = figure;
panel = uipanel('Parent',fig);
hAxes = axes('Parent',panel,'Color','green');
%Calculate Steering Weights
w = zeros(getNumElements(h), length(F));
SV = phased.SteeringVector('SensorArray',h, 'PropagationSpeed', PS);
%Find the weights
for idx = 1:length(F)
    w(:, idx) = step(SV, F(idx), SA(:, idx));
end
%Plot 3d graph
fmt = 'polar';
pattern(h, F(1), 'PropagationSpeed', PS, 'Type','directivity', ...
    'CoordinateSystem', fmt,'weights', w(:,1));
%Adjust the view angles
hSmallAxes = axes('Parent', panel, 'Position', [0 0.8 0.2 0.2]);
hlink = linkprop([hAxes hSmallAxes],'View');
setappdata(fig, 'Lin1', hlink);
viewArray(h,'AxesHandle', hSmallAxes)
view(hAxes,[135 20]);
title = get(hAxes, 'title');
title_str = get(title, 'String');
%Modify the title
[Fval, ~, Fletter] = engunits(66000000000);
steeringString = 'steered at 30 Az, 30 El';
title_str = [title_str sprintf('\n') num2str(Fval) ' ' Fletter 'Hz ' ...
    steeringString];
set(title, 'String', title_str);
